In [34]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

sns.set_theme(style="whitegrid")

df = pd.read_csv("../data/E-commerce_Customer_Segmentation_2026.csv")
print(f"Dataset Shape: {df.shape[0]} rows, {df.shape[1]} columns\n")
print("Data Types & Missing Values:")
df.info()
df.head()

Dataset Shape: 50000 rows, 53 columns

Data Types & Missing Values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 53 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    50000 non-null  object
 1   customer_segment               50000 non-null  object
 2   segment_category               50000 non-null  object
 3   age                            50000 non-null  int64
 4   age_group                      50000 non-null  object
 5   gender                         50000 non-null  object
 6   country                        50000 non-null  object
 7   city                           50000 non-null  object
 8   income_bracket                 50000 non-null  object
 9   education_level                50000 non-null  object
 10  employment_type                50000 non-null  object
 11  marital_status                 50000 non-null  object
 12  tenure_months                  50000 non-null  int64
 13  total_purchases                50000 non-null  int64
 14  avg_order_value_usd            50000 non-null  float64
 15  total_spent_usd                50000 non-null  float64
 16  purchase_frequency             50000 non-null  object
 17  days_since_last_purchase       50000 non-null  int64
 18  preferred_category_1           50000 non-null  object
 19  preferred_category_2           33257 non-null  object
 20  preferred_category_3           16743 non-null  object
 21  shopping_channel               50000 non-null  object
 22  device_used                    50000 non-null  object
 23  payment_method                 50000 non-null  object
 24  return_count                   50000 non-null  int64
 25  complaint_count                50000 non-null  int64
 26  satisfaction_score             50000 non-null  int64
 27  satisfaction_level             50000 non-null  object
 28  loyalty_tier                   48728 non-null  object
 29  email_open_rate                50000 non-null  float64
 30  click_through_rate             50000 non-null  float64
 31  conversion_rate                50000 non-null  float64
 32  social_media_presence          37580 non-null  object
 33  customer_lifetime_value_usd    50000 non-null  float64
 34  customer_acquisition_cost_usd  50000 non-null  float64
 35  customer_profitability_usd     50000 non-null  float64
 36  recency_score                  50000 non-null  int64
 37  frequency_score                50000 non-null  int64
 38  monetary_score                 50000 non-null  int64
 39  rfm_score                      50000 non-null  int64
 40  churn_risk_score               50000 non-null  int64
 41  customer_health_score          50000 non-null  int64
 42  dataset_year                   50000 non-null  int64
 43  customer_value_category        50000 non-null  object
 44  activity_status                50000 non-null  object
 45  health_status                  50000 non-null  object
 46  churn_risk_category            50000 non-null  object
 47  rfm_category                   50000 non-null  object
 48  profitability_category         50000 non-null  object
 49  engagement_level               50000 non-null  object
 50  behavior_segment               50000 non-null  object
 51  device_preference              50000 non-null  object
 52  clv_category                   50000 non-null  object
dtypes: float64(8), int64(14), object(31)
memory usage: 20.2+ MB

,customer_id,customer_segment,segment_category,age,age_group,gender,country,city,income_bracket,education_level,...,customer_value_category,activity_status,health_status,churn_risk_category,rfm_category,profitability_category,engagement_level,behavior_segment,device_preference,clv_category
0,CUST-000001,Consumer,High Value Inactive,70,65+,Male,Canada,Winnipeg,150K+,Professional,...,High,Dormant,Excellent,Low,Potential Loyalists,High Profit,Low,Regular Buyer,Multi-Device,High CLV
1,CUST-000002,Premium,High Value Inactive,53,45-54,Female,Germany,Essen,25K-50K,High School,...,Medium,Inactive,Excellent,Medium,At Risk,High Profit,Low,Occasional Buyer,Desktop-First,High CLV
2,CUST-000003,Consumer,High Value Inactive,82,65+,Male,Mexico,Puebla,75K-100K,Bachelors,...,Very High,Dormant,Excellent,Very Low,Champions,High Profit,Low,Regular Buyer,Multi-Device,High CLV
3,CUST-000004,Enterprise,High Value Active,18,18-24,Male,Singapore,Singapore,150K+,Masters,...,Very High,Active,Excellent,Very Low,Champions,High Profit,High,Frequent Buyer,Mobile-First,High CLV
4,CUST-000005,Premium,High Value Active,64,55-64,Male,United Arab Emirates,Fujairah,150K+,PhD,...,Medium,Active,Fair,Medium,Loyal,High Profit,Medium,Occasional Buyer,Desktop-First,High CLV

In [35]:
df=df.drop(columns=['customer_id', 'rfm_score', 'customer_health_score','churn_risk_score','rfm_category','health_status','satisfaction_level'])
df.shape

(50000, 46)

In [36]:
df.isnull().sum()

customer_segment                     0
segment_category                     0
age                                  0
age_group                            0
gender                               0
country                              0
city                                 0
income_bracket                       0
education_level                      0
employment_type                      0
marital_status                       0
tenure_months                        0
total_purchases                      0
avg_order_value_usd                  0
total_spent_usd                      0
purchase_frequency                   0
days_since_last_purchase             0
preferred_category_1                 0
preferred_category_2             16743
preferred_category_3             33257
shopping_channel                     0
device_used                          0
payment_method                       0
return_count                         0
complaint_count                      0
satisfaction_score                   0
loyalty_tier                      1272
email_open_rate                      0
click_through_rate                   0
conversion_rate                      0
social_media_presence            12420
customer_lifetime_value_usd          0
customer_acquisition_cost_usd        0
customer_profitability_usd           0
recency_score                        0
frequency_score                      0
monetary_score                       0
dataset_year                         0
customer_value_category              0
activity_status                      0
churn_risk_category                  0
profitability_category               0
engagement_level                     0
behavior_segment                     0
device_preference                    0
clv_category                         0
dtype: int64

In [37]:
df['preferred_category_2'] = df['preferred_category_2'].fillna('Unknown')
df['preferred_category_3'] = df['preferred_category_3'].fillna('Unknown')
df.isnull().sum()

customer_segment                     0
segment_category                     0
age                                  0
age_group                            0
gender                               0
country                              0
city                                 0
income_bracket                       0
education_level                      0
employment_type                      0
marital_status                       0
tenure_months                        0
total_purchases                      0
avg_order_value_usd                  0
total_spent_usd                      0
purchase_frequency                   0
days_since_last_purchase             0
preferred_category_1                 0
preferred_category_2                 0
preferred_category_3                 0
shopping_channel                     0
device_used                          0
payment_method                       0
return_count                         0
complaint_count                      0
satisfaction_score                   0
loyalty_tier                      1272
email_open_rate                      0
click_through_rate                   0
conversion_rate                      0
social_media_presence            12420
customer_lifetime_value_usd          0
customer_acquisition_cost_usd        0
customer_profitability_usd           0
recency_score                        0
frequency_score                      0
monetary_score                       0
dataset_year                         0
customer_value_category              0
activity_status                      0
churn_risk_category                  0
profitability_category               0
engagement_level                     0
behavior_segment                     0
device_preference                    0
clv_category                         0
dtype: int64

In [38]:
df[['preferred_category_2', 'preferred_category_3']].isnull().sum()

preferred_category_2    0
preferred_category_3    0
dtype: int64

In [39]:
df.describe()

,age,tenure_months,total_purchases,avg_order_value_usd,total_spent_usd,days_since_last_purchase,return_count,complaint_count,satisfaction_score,email_open_rate,click_through_rate,conversion_rate,customer_lifetime_value_usd,customer_acquisition_cost_usd,customer_profitability_usd,recency_score,frequency_score,monetary_score,dataset_year
count,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.0
mean,45.64802,59.748240,99.418460,505.366911,50266.546156,62.971240,9.511740,6.99380,3.007960,0.500319,0.250748,0.150368,57722.068910,102.453505,57619.615405,3.954040,4.122720,3.717700,2026.0
std,18.36795,34.310128,57.780178,285.604037,44071.209164,93.281404,5.782592,4.32425,1.417976,0.289515,0.144259,0.086877,52437.283546,56.373987,52437.172654,1.478949,1.077573,1.358633,0.0
min,18.00000,1.000000,0.000000,10.050000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,5.010000,-199.870000,1.000000,1.000000,1.000000,2026.0
25%,30.00000,30.000000,49.000000,259.067500,13893.577500,2.000000,4.000000,3.00000,2.000000,0.251000,0.127000,0.075000,15488.650000,53.820000,15372.800000,3.000000,3.000000,3.000000,2026.0
50%,45.00000,60.000000,99.000000,504.790000,37541.625000,19.000000,10.000000,7.00000,3.000000,0.500000,0.251000,0.150000,42236.310000,102.320000,42129.690000,5.000000,4.000000,4.000000,2026.0
75%,60.00000,90.000000,150.000000,752.702500,76811.242500,77.000000,15.000000,11.00000,4.000000,0.752000,0.375250,0.226000,86714.875000,151.260000,86608.330000,5.000000,5.000000,5.000000,2026.0
max,84.00000,119.000000,199.000000,999.990000,198574.140000,365.000000,19.000000,14.00000,5.000000,1.000000,0.500000,0.300000,294634.150000,200.000000,294479.720000,5.000000,5.000000,5.000000,2026.0

In [40]:
df = pd.get_dummies(df, columns=['preferred_payment_method'],drop_first=True)

KeyError: "None of [Index(['preferred_payment_method'], dtype='object')] are in the [columns]"

In [41]:
# Check unique value counts for all non-numeric columns
df.select_dtypes(include=['object', 'category']).nunique()

customer_segment             4
segment_category             6
age_group                    6
gender                       2
country                     17
city                       157
income_bracket               6
education_level              5
employment_type              5
marital_status               4
purchase_frequency           5
preferred_category_1        12
preferred_category_2        13
preferred_category_3        13
shopping_channel             4
device_used                  4
payment_method               5
loyalty_tier                 5
social_media_presence      156
customer_value_category      5
activity_status              4
churn_risk_category          5
profitability_category       5
engagement_level             3
behavior_segment             4
device_preference            3
clv_category                 3
dtype: int64

In [42]:
df = df.drop(columns=['social_media_presence', 'country', 'city'])

In [43]:
categorial_columns = df.select_dtypes(include=['object', 'category']).columns

df = pd.get_dummies(df, columns=categorial_columns,drop_first=True)

df.shape
df.columns

Index(['age', 'tenure_months', 'total_purchases', 'avg_order_value_usd',
       'total_spent_usd', 'days_since_last_purchase', 'return_count',
       'complaint_count', 'satisfaction_score', 'email_open_rate',
       ...
       'profitability_category_Medium Profit', 'engagement_level_Low',
       'engagement_level_Medium', 'behavior_segment_New Buyer',
       'behavior_segment_Occasional Buyer', 'behavior_segment_Regular Buyer',
       'device_preference_Mobile-First', 'device_preference_Multi-Device',
       'clv_category_Low CLV', 'clv_category_Medium CLV'],
      dtype='object', length=126)

In [44]:
x = df.drop(columns=['satisfaction_score'])
y = df['satisfaction_score']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((40000, 125), (10000, 125), (40000,), (10000,))

In [45]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [46]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [47]:
y_pred = model.predict(X_test_scaled)
y_pred = model.predict(X_test_scaled)

In [48]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print("MSE:", mse)

MSE: 1.170541119281402

In [49]:
import pandas as pd

# Match feature names with their learned coefficients
feature_importances = pd.Series(model.coef_, index=x.columns)

# Display the top 5 largest positive coefficients
print(feature_importances.abs().sort_values(ascending=False).head(5))

churn_risk_category_Very Low    1.785344
churn_risk_category_Low         1.040054
purchase_frequency_Rarely       0.738691
churn_risk_category_Medium      0.390482
return_count                    0.302396
dtype: float64

In [50]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.42186304621587845

In [51]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

rf_model.fit(X_train_scaled, y_train)

y_pred_rf = rf_model.predict(X_test_scaled)

rf_mse = mean_squared_error(y_test, y_pred_rf)
rf_r2 = r2_score(y_test, y_pred_rf)

print("Random Forest MSE:", rf_mse)
print("Random Forest R2 Score:", rf_r2)

Random Forest MSE: 0.9946089499999998
Random Forest R2 Score: 0.5087569508771892

In [52]:
rf_importances = pd.Series(rf_model.feature_importances_, index=x.columns)
print(rf_importances.abs().sort_values(ascending=False).head(5))

churn_risk_category_Very Low    0.223104
return_count                    0.087783
complaint_count                 0.085301
days_since_last_purchase        0.055148
churn_risk_category_Low         0.045066
dtype: float64